package group.msg.at.cloud.cloudtrain.core.entity;

import java.util.Locale;
import java.util.UUID;

/**
 * Simple {@code entity} representing a welcome message.
 * <p>
 * And YES: the author is aware of frameworks like {@code Lombok} which help to write DRY java code.
 * For the sake of simplicity, this class uses the old-school approach with explicit setters and getters
 * (which are generated by the way!).
 * </p>
 */
public class Message {

    private UUID id;

    private String code;

    private String text;

    private Locale locale;

    public Message() {
        super();
    }

    public Message(UUID id) {
        this.id = id;
    }

    public UUID getId() {
        return id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Locale getLocale() {
        return locale;
    }

    public void setLocale(Locale locale) {
        this.locale = locale;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        Message other = (Message) obj;
        if (id == null) {
            return other.id == null;
        } else return id.equals(other.id);
    }

    @Override
    public String toString() {
        return getClass().getSimpleName() + " { id : \"" + this.id + "\" }";
    }
}
