apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cnj-hello-backend-micro
  labels:
    helm.sh/chart: cnj-hello-backend-micro-4.0.0
    app.kubernetes.io/name: cnj-hello-backend-micro
    app.kubernetes.io/instance: cnj-hello-backend-micro
    app.kubernetes.io/version: "6.0.0"
    app.kubernetes.io/managed-by: kubectl
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/x-forwarded-prefix: /cloudtrain/cnj-hello-backend-micro
spec:
  ingressClassName: nginx
  rules:
    - host: "apps.cloudtrain.aws.msgoat.eu"
      http:
        paths:
          - path: /cloudtrain/cnj-hello-backend-micro(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: cnj-hello-backend-micro
                port:
                  name: http
